repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [ "--py37-plus" ]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [ --safe ]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black==23.7 ]
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "1.1.0"
    hooks:
      - id: pyproject-fmt
        additional_dependencies: ["tox>=4.11"]
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.1"
    hooks:
      - id: tox-ini-fmt
        args: [ "-p", "fix" ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.7.10
          - flake8-comprehensions==3.14
          - flake8-pytest-style==1.7.2
          - flake8-unused-arguments==0.0.13
          - flake8-noqa==1.3.2
          - pep8-naming==0.13.3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: ui-tests-ipw[78]\/.*
        additional_dependencies:
          - "pandas-stubs>=2.0.3.230814"
          - "types-Pygments>=2.16"
          - "types-colorama>=0.4.15.12"
          - "types-setuptools>=68.1.0.1"
